app/blueprints/api.py
from app.models.app import Visit
import re
from flask import current_app as app, Blueprint, render_template, url_for, redirect, flash, json, Markup, abort, request, escape, g, jsonify, session, make_response
from flask.globals import current_app
from flask_security import login_required, current_user
from flask_security import roles_accepted
from app.core.db import db
from app.models.notifier import Notifier, NotifierPriority, NotifierStatus
from app.models.wiki import Question, QuestionLike, QuestionSave, QuestionView, Tag, Topic
from app.models.security import User
from app.models.app import Network
from app.models.search import Search
from app.utils.kernel import order_dict
from app.utils.routes import counter
from datetime import datetime
# import time

bp = Blueprint('api', __name__, url_prefix='/api/')

@bp.errorhandler(404)
def resource_not_found(e):
    return {'error_cod': 404, 'error': 'Não encontrado'}, 404
@bp.errorhandler(500)
def server_error(e):
    return {'error_cod': 500, 'error': 'Erro interno'}, 500

@bp.route('question/<int:id>', methods=['GET', 'POST'])
@counter
def question(id):
    if session.get("AccessType", False) is False:
        abort(500)
    # access_type = session.get("AccessType", False)
    question = Question.query.filter(Question.id == id).first()

    if question is None:
        return abort(404)
    if (question.answer_approved == False or question.active != True or question.was_answered != True) and not current_user.is_authenticated:
        abort(404)
    if current_user.is_authenticated:
        question.add_view(current_user.id, g.ip_id)
        to_dict = question.to_dict()
        if question.is_liked(current_user.id):
            to_dict['like_action'] = 'unlike'
        else:
            to_dict['like_action'] = 'like'
        if question.is_saved(current_user.id):
            to_dict['save_action'] = 'unsave'
        else:
            to_dict['save_action'] = 'save'
        to_dict['url_like'] = url_for('question.like_action', question_id=id)
        to_dict['url_save'] = url_for('question.save_action', question_id=id)
        if current_user.can_edit:
            to_dict['url_edit'] = url_for('question.edit', id=id)
    else:
        question.add_view(app.config.get('USER_ANON_ID'), g.ip_id)
        to_dict = question.to_dict()
    to_dict['url_view'] = url_for('question.view', id=id)
    return jsonify(to_dict)


@bp.route('json/questions/access')
def question_access():
    return ''

@bp.route('notifications')
# @counter
def notifications():
    if session.get("AccessType", False) is False:
        abort(500)
    notifier = db.session.query(Notifier).join(NotifierStatus).join(NotifierPriority).filter(NotifierStatus.status == 'Ativo', Notifier.autoload != True).order_by(NotifierPriority.order.asc())
    to_dict = [_.to_dict for _ in notifier]
    return jsonify(to_dict)


@bp.route('notification/<int:id>')
@counter
def notification(id:int):
    obj_notification = db.session.query(Notifier).join(NotifierStatus).filter(NotifierStatus.status == 'Ativo', Notifier.id == id).first()
    # Notifier.query.filter(Notifier.id == id, Notifier.).first()
    if obj_notification is None:
        return jsonify([]), 404
    else:
        return jsonify(obj_notification.to_dict_detail)


@bp.route('notifications/autoload')
# @counter
def notifications_autoload():
    obj_notification = db.session.query(Notifier).join(NotifierStatus).join(NotifierPriority).filter(NotifierStatus.status == 'Ativo', Notifier.autoload == True).order_by(NotifierPriority.order.asc())
    to_dict = [_.to_dict_detail for _ in obj_notification]
    return jsonify(to_dict)

@bp.route('set_bg/<string:value>', methods=["GET", "POST"])
def set_bg(value):
    confirm = request.form.get("confirm", False)
    if confirm != "true":
        return jsonify({"status": "error", "message": "Não é possível acessar"}), 404
    if value in ['white', 'dark']:
        resp = {'value':True}
        resp = make_response({'value': True})
        resp.set_cookie('bg', value)
        return resp
    return {'value': False}






# # api dashboard
# @bp.route('dashboard/tags_data', methods=['GET', 'POST'])
# def tags_data():
#     '''
#     Gera dados das 10 maiores categorias, caso tenham mais de 10 categorias a 10ª será Outros
#     '''
#     questions = Tag._dict_count_questions()
#     questions = order_dict(Tag._dict_count_questions(), 5)
#     return jsonify({
#         'labels': list(questions.keys()),
#         'datasets': [{
#             'data': list(questions.values()),
#             'backgroundColor': [
#                 "blue",
#                 "purple",
#                 "pink",
#                 "red",
#                 "orange",
#                 "yellow",
#                 "green",
#                 "cyan",
#                 "gray",
#                 "black"
#             ]  # ,
#             # 'hoverBackgroundColor': [
#             #     "#CFD4D8",
#             #     "#B370CF",
#             #     "#E95E4F",
#             #     "#36CAAB",
#             #     "#49A9EA"
#             # ]
#         }],
#         'totalQuestions': Question.query.count()
#     })




# @bp.route('dashboard/visit', methods=['GET', 'POST'])
# def visits_by_interval():
#     if request.method == 'POST':
#         start = request.form.get('start', False)
#         end = request.form.get('end', False)
#         if start is False or end is False:
#             return jsonify({
#                 'error': True,
#                 'mensage': 'Data inicial ou final inválida;'
#             })
#         return jsonify([[_[1].strftime('%Y-%m-%dT%H:%M:%S.%f'),
#                         _[0]] for _ in Visit.total_by_date(start, end).all()])


# @bp.route('dashboard/visits', methods=['GET', 'POST'])
# def visits_data():
#     if request.method == 'POST':
#         year = request.form.get('year', False)
#         month = request.form.get('month', None)
#         start = request.form.get('start', False)
#         end = request.form.get('end', False)
#         if not year.isnumeric():
#             return jsonify({
#                 'error': True,
#                 'message': 'Ano inválido'
#             })
#         year = int(year)
#         if year is False:
#             return jsonify({
#                 'error': True,
#                 'message': 'Ano inválido'
#             })
#         if month is None:
#             return jsonify([[_[1].strftime('%Y-%m-%dT%H:%M:%S.%f'),_[0]] for _ in Visit.total_by_year_month(year=year).all()])
#             try:
#                 return jsonify({_[1]:_[0] for _ in Visit.total_by_year_month(year=year).all()})
#             except Exception as e:
#                 return jsonify({
#                     'error': True,
#                     'message': 'Valor inválido Mês'
#                 })
#         if not month.isnumeric():
#             return jsonify(
#                 {'error':True, 
#                 'message': 'Mês inválido'}
#             )
#         try:
#             month = int(month)
#             return jsonify([[_[1].strftime('%Y-%m-%dT%H:%M:%S.%f'),_[0]] for _ in Visit.total_by_year_month(year=year, month=month).all()])
#         except Exception as e:
#             return jsonify({
#                 'error': True,
#                 'message': 'Valor inválido'
#             })
#     return ''

app/blueprints/auth.py
from logging import error
from flask import current_app as app, Blueprint, render_template, url_for, redirect, flash, json, request, g, session as fsession
from flask_login.utils import login_required
from flask_security import current_user, login_user, logout_user
from sqlalchemy.orm import session
from werkzeug.urls import url_parse
from datetime import datetime

from app.models.security import User
from app.forms.login import LoginForm
from app.forms.reset_password import ResetPassword
from app.utils.kernel import convert_datetime_to_local, validate_password
from app.utils.routes import counter
from app.core.db import db

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.before_request
@counter
def before_request():
    pass

@bp.route('/login/', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    login = LoginForm()
    if login.validate_on_submit():
        user = User.query.filter_by(username=login.username.data).first()
        if user is None or not user.check_password(login.password.data):
            flash('Senha ou usuário inválido', category='danger')
            return render_template('login.html', form=login, title='Login')#redirect(url_for('auth.login'))
        if not user.is_active:
            flash('Usuário inativo', category='danger'),
            return redirect(url_for('auth.login'))
        if user.is_temp_password:
            flash('É necessário alterar sua senha.', category='info')
            fsession['temp_user'] = user.username
            return redirect(url_for('auth.temp_password'))
        login_user(user, remember=login.remember_me.data)
        user.last_login_ip = request.remote_addr
        user.last_login_at = convert_datetime_to_local(datetime.utcnow())
        user.current_login_at = convert_datetime_to_local(datetime.utcnow())
        user.current_login_ip = request.remote_addr
        # user.login_count += 1
        try:
            db.session.commit()
        except Exception as e:
            app.logger.error(app.config.get('_ERRORS').get('DB_COMMIT_ERROR'))
            app.logger.error(e)
            logout_user()
            return redirect(url_for('auth.login'))
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('main.index')
        return redirect(next_page)
    return render_template('login.html', form=login, title='Login')

@bp.route('/temp_password/', methods=['GET', 'POST'])
def temp_password():
    if current_user.is_authenticated:
        flash(message='Usuário logado', category='danger')
        return redirect(url_for('auth.login'))
    username = fsession.get('temp_user', False)
    if username is False:
        message = 'Nenhum usuário encontrado'
        flash(message=message, category='danger')
        return redirect(url_for('auth.login'))

    user = User.query.filter(User.username == username).first()
    if user is None:
        message = 'Nenhum usuário encontrado'
        flash(message=message, category='danger')
        return redirect(url_for('auth.login'))
    if not user.is_temp_password:
        message = 'Usuário não tem senha provisória'
        flash(message=message, category='danger')
        return redirect(url_for('auth.login'))
    
    form = ResetPassword()
    form.username.data = user.username
    if form.validate_on_submit():
        if form.new_password.data == form.confirm_new_password.data:
            if not user.check_password(form.old_password.data):
                # senha antiga não é igual a senha do usuário
                message = 'Senha atual incorreta'
                # flash(message=message, category='danger')
                form.old_password.errors.append(message)
                return render_template('reset_password.html', form=form)
            if form.new_password.data == form.old_password.data:
                # senha nova é igual a senha antiga.
                message = "A nova senha deve ser diferente da senha anterior"
                # flash(message=message, category='danger')
                # return render_template('reset_password.html', form=form)
                form.old_password.errors.append(message)
                return render_template('reset_password.html', form=form)
            _validate_password = validate_password(form.new_password.data)
            if not _validate_password.get('ok', False) is True:
                message = app.config['MSG_PASSWORD_VALIDATE']
                flash(message=message, category='danger')
                form.new_password.errors.append(message)
                return render_template('reset_password.html', form=form)
            print(validate_password(form.new_password.data))
            user.password = form.new_password.data
            user.temp_password = False
            try:
                db.session.commit()
                flash(message='Senha alterada com sucesso, acesse novamente', category='info')
                return redirect(url_for('auth.login'))
            except Exception as e:
                app.logger.error(app.config.get('_ERRORS').get('DB_COMMIT_ERROR'))
                app.logger.error(e)
                return redirect(url_for('auth.login'))
        else:
            form.confirm_new_password.errors.append('Senha não confere com a senha informada.')
            return render_template('reset_password.html', form=form)
    return render_template('reset_password.html', form=form)

@bp.route('/change_password/', methods=['GET', 'POST'])
@login_required
def change_password():
    
    if not current_user.is_authenticated:
        flash(message='Usuário não logado', category='danger')
        return redirect(url_for('main.index'))
    
    form = ResetPassword()
    form.username.data = current_user.username
    if form.validate_on_submit():
        if form.new_password.data == form.confirm_new_password.data:
            if not current_user.check_password(form.old_password.data):
                # senha antiga não é igual a senha do usuário
                message = 'Senha atual incorreta'
                flash(message=message, category='danger')
                return redirect(url_for('auth.login'))
            if form.new_password.data == form.old_password.data:
                # senha nova é igual a senha antiga.
                message = "A nova senha deve ser diferente da senha anterior"
                flash(message=message, category='danger')
                return redirect(url_for('auth.login'))
            current_user.password = form.new_password.data
            current_user.temp_password = False
            try:
                db.session.commit()
                flash(message='Senha alterada com sucesso, acesse novamente', category='info')
                return redirect(url_for('auth.login'))
            except Exception as e:
                app.logger.error(app.config.get('_ERRORS').get('DB_COMMIT_ERROR'))
                app.logger.error(e)
                return redirect(url_for('auth.login'))
        else:
            form.confirm_new_password.errors.append('Senha não confere com a senha informada.')
            return render_template('reset_password.html', form=form)
    return render_template('reset_password.html', form=form)

@bp.route('/logout/')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

app/templates/base/navbar.html
{% block navbar %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top border-bottom">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarCollapse">
            <a class="navbar-brand" href="{{url_for('main.index')}}">{{config['SITE_TITLE']}}</a>
            <ul class="navbar-nav me-auto mb-md-0  navbar-nav-scroll">
                <li class="nav-item">
                    <a class="btn btn-sm btn-outline-secondary me-2" type="button" href="{{ url_for('question.index')}}"
                        class='nav-link'>Dúvidas</a>
                </li>

                <div class="dropdown nav-item">
                    <button class="btn btn-outline-success dropdown-toggle" type="button" id="dropdownMenuButton1"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Menu
                    </button>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton1">
                        {% if g.upload_urls %}
                        <li class="dropdown-submenu dropdown-item">

                            <a class="dropdown-item" href="#">Arquivos</a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                {% for item in g.upload_urls.items() %}
                                <li><a class="dropdown-item"
                                        href="{{url_for('file_pdf.files', file_type= item[1])}}">{{item[0]}}</a></li>
                                {% endfor %}
                            </ul>
                            {% endif %}
                        </li>
                        {% if current_user.is_authenticated %}
                        {% if current_user.is_support %}
                        <li>
                            <hr class="dropdown-divider" />
                        </li>
                        <li>
                            <a class="dropdown-item" type="button" href="{{ url_for('support.index')}}">Suporte</a>
                        </li>
                        {% endif %}

                        <li>
                            <a class="dropdown-item" type="button" href="{{ url_for('dashboard')}}"
                                class='nav-link'>Dashboard</a>
                        </li>
                        <li><a class='dropdown-item' type='button' href="{{ url_for('notifier.index')}}"
                                class='nav-link'>Notificações</a>
                        </li>


                        {% if config.get('MODE', False) == 'dev' %}
                        <li>
                            <hr class="dropdown-divider" />
                        </li>
                        <li class="dropdown-submenu dropdown-item">
                            <a class="dropdown-item" href="#">Desenvolvimento</a>
                            <ul class="dropdown-menu dropdown-menu-dark">

                                <li><a class="dropdown-item" type='button' href="{{ url_for('admin.transaction')}}"
                                        class='nav-link'>Transações</a>
                                </li>
                            </ul>
                        </li>
                        {% endif %}
                        {% endif %}
                    </ul>
                </div>
                
            </ul>
            {% if config.get('MODE', False) == 'dev' %}

            {% endif %}
            <div class="navbar-nav col-6 w-50 justify-content-center">

                <form class="row row-cols-lg-auto g-3" method="GET" action="{{ url_for('question.search') }}">
                    <div class="col">
                        {{ render_field(g.question_search_form.filter, class='selectpicker', nolabel=true,
                        multiple=true, **{'data-actions-box':"true", 'data-style':"btn-primary",
                        'data-selected-text-format':"count"})}}
                    </div>
                    <div class="col">
                        <!-- <i class="fa fa-search"></i> -->
                        <div class="input-group mb-3">
                            {{ render_field(g.question_search_form.q, size=15, class='form-control',
                            placeholder='Buscar...', nolabel=true, type='search', **{'aria-label':"Buscar",
                            'aria-describedby':"submit"})}}
                            <div class="input-group-append">
                                {{ render_field(g.question_search_form.submit, class='btn btn-primary',
                                nolabel=true, id='submit')}}
                            </div>
                        </div>
                        <!-- <input type="search" placeholder="Buscar..." class="form-control me-2" id="search" name="search"> -->
                        <!-- <button class="btn btn-primary">Search</button> -->
                    </div>
                </form>
                <!-- </div> -->
            </div>


            <ul class="navbar-nav w-100 justify-content-center">
                <li class="nav-item dropdown bell" id="bell-dropdown">
                    <!-- <div class="icon" id="bell">  -->
                    <a class="nav-link notifications-link" href="{{url_for('api.notifications')}}" id="bell"
                        data-bs-toggle="dropdown" aria-expanded="false">

                        <i class="fas fa-bell circle bg_red">
                            <span class="badge badge-danger">{{g.sum_active_notifier}}</span>
                        </i>

                    </a>
                    <ul class="dropdown-menu show-bell" aria-labelledby="dropdown01">
                        <div class="notifications" id="notification_box">
                            <!-- <h2>Notificações - <span>{{g.sum_active_notifier}}</span></h2>
                            {% if g.notifiers_dict | length == 0 %}
                            ZERO
                            {% else %}
                            {% for notifier in g.notifiers_dict %}
                            <div class="notifications-item">
                                <div class="text">
                                    <h6>{{notifier['title']}}</h6>
                                    <p>{{notifier['content']}}</p>
                                </div>
                            </div>

                            {% endfor %}
                            {% endif %} -->
                        </div>
                    </ul>
                    <!-- </div> -->
                </li>
                {% if current_user.is_anonymous %}
                <li class="nav-item">
                    <a href="{{ url_for('auth.login') }}" class="nav-link">Login</a>
                </li>
                {% else %}
                {% if current_user.has_support %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <i class="fas fa-tools circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown01">
                        <li><a class="dropdown-item" href="{{url_for('admin.questions')}}">Perguntas</a></li>
                        <li><a class="dropdown-item" href="{{url_for('admin.to_approve')}}">Pendentes</a></li>
                        <li><a class="dropdown-item" href="{{url_for('admin.answers')}}">Respondidas</a></li>
                        {% if current_user.has_role('admin') %}
                        <li><a class="dropdown-item" href="{{url_for('admin.users')}}">Usuários</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{{url_for('admin.tag')}}">Marcação</a></li>
                        <li><a class="dropdown-item" href="{{url_for('admin.topic')}}">Tópico</a></li>
                        <li><a class="dropdown-item" href="{{url_for('admin.sub_topic')}}">Sub Tópico</a></li>
                        <li><a class="dropdown-item" href="{{url_for('admin.file_pdf_type')}}"> Tipo de Arquivo</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        {% endif %}
                        <li><a class="dropdown-item" href='{{url_for("admin.notifier")}}'>Notificações</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('admin.transaction')}}">Transações</a>
                    </li>
                        <hr class="dropdown-divider">
                        <li><a class="dropdown-item" href='{{url_for("admin.file")}}'>Upload</a></li>
                        {% if config.get('MODE', False) == 'dev' %}
                        <!-- #TODO apenas em DEV -->
                        <hr class="dropdown-divider">
                        
                        
                        {% endif %}

                    </ul>

                </li>

                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <!-- <img src="https://github.com/mdo.png" alt="mdo" class="rounded-circle" width="32" height="32"> -->
                        <i class="fas fa-user circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown01">
                        <li><a class="dropdown-item" href="{{ url_for('user.profile') }}">{{
                                _('Perfil') }}</a></li>
                        <li>
                            <a class="dropdown-item" href="{{url_for('question.saves')}}">{{_('Salvos') }}
                                <span class="badge bg-info text-dark">{{current_user.questions_saved_count}}</span>
                            </a>
                        </li>
                        <li><a class="dropdown-item" href="{{url_for('question.likes')}}">{{_('Curtidas') }}
                                <span class="badge bg-info  text-dark">{{current_user.questions_liked_count}}</span>

                            </a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">{{ _('Sair') }}</a></li>
                    </ul>

                </li>

                {% endif %}
                
            </ul>
        </div>

    </div>
    
</nav>




{% endblock %}