app/blueprints/notifier.py
from datetime import datetime
from flask.json import jsonify
from app.utils.html import process_html
from app.utils.kernel import convert_datetime_to_local
from app.utils.routes import counter
from flask.helpers import flash, url_for
from werkzeug.utils import redirect
from app.models.app import Network
from app.models.notifier import Notifier, NotifierLevel, NotifierPriority, NotifierStatus
from app.forms.notifier import NotifierForm
from flask import Blueprint, render_template, g, request, current_app as app, abort
from app.core.db import db
from flask_security import login_required, roles_accepted, current_user
from app.utils.routes import counter


bp = Blueprint('notifier', __name__, url_prefix='/notificacao')

@bp.route('/')
def index():
    notices_active = db.session.query(Notifier).join(NotifierStatus, Notifier.status).join(NotifierPriority, Notifier.priority).filter(NotifierStatus.status == 'Ativo').order_by(NotifierPriority.order.asc(), Notifier.create_at.desc())
    # Notifier.query.filter(NotifierStatus.status == 'Ativo')
    notices_history = db.session.query(Notifier).join(NotifierStatus, Notifier.status).join(NotifierPriority, Notifier.priority).filter(NotifierStatus.status == 'Histórico').order_by(NotifierPriority.id.asc())
    # Notifier.query.filter(NotifierStatus.status == 'Histórico')
    return render_template('notifier.html', notices_active = notices_active, notices_history = notices_history)


@bp.route('/add', methods=['GET', 'POST'])
@login_required
@roles_accepted('admin', 'support')
def add():
    form = NotifierForm()
    error = False
    if form.validate_on_submit():
        nf = Notifier.query.filter(Notifier.title.ilike(form.title.data.lower())).first()
        if not nf is None:
            error = True
            form.title.errors.append('Titulo inválido ou já existente')
            return render_template('add.html', form=form, title='Adicionar', notifier=True)
        nf = Notifier.query.filter(Notifier.content.ilike(form.content.data.lower())).first()
        if not nf is None:
            error = True
            form.content.errors.append('Conteudo inválido ou já existente')
            return render_template('add.html', form=form, title='Adicionar', notifier=True)
        nf = Notifier()
        nf.title = form.title.data
        nf.content = form.content.data
        nf.status = form.status.data
        nf.level = form.level.data
        nf.priority = form.priority.data
        nf.topics.extend(form.topics.data)
        nf.sub_topics.extend(form.sub_topics.data)
        nf.created_user_id = current_user.id
        if form.autoload.data == True:
            temp_nf = Notifier.query.filter(Notifier.sub_topics.contains(*form.sub_topics.data), Notifier.autoload == True).first()
            if not temp_nf is None:
                # status = NotifierStatus.query.filter(NotifierStatus.status == 'Histórico').first()
                # temp_nf.status =status
                temp_nf.autoload = False
        nf.autoload = form.autoload.data
        _ip = Network.query.filter(Network.id == g.ip_id).first()
        if _ip is None:
            _ip = Network()
            _ip.ip = request.access_route[0] or request.remote_addr
            db.session.add(_ip)
            try:
                db.session.commit()
                g.ip_id = _ip.id
            except Exception as e:
                db.session.rollback()
                app.logger.error(app.config.get("_ERRORS").get("DB_COMMIT_ERROR"))
                app.logger.error(e)
                return abort(500)
        nf.created_network_id = _ip.id
        if not error:
            try:
                db.session.add(nf)
                db.session.commit()
                flash('Notificação criada com sucesso', category='success')
                return redirect(url_for('admin.notifier'))
            except Exception as e:
                app.logger.error(app.config.get('_ERRORS').get('DB_COMMIT_ERROR'))
                app.logger.error(e)
                db.session.rollback()
                form.errors.add('Não foi possível concluir')
                return render_template('add.html', form=form, title='Adicionar', notifier=True)

    return render_template('add.html', form=form, title='Adicionar', notifier=True)

@bp.route('/view/<int:id>')
@login_required
@roles_accepted('admin', 'support')
@counter
def view(id: int):
    notification = Notifier.query.filter(Notifier.id == id).first_or_404()

    return render_template('notifier.html', notification_dict=notification.to_dict_detail)

@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
@roles_accepted('admin', 'support')
def edit(id: int):
    nf = Notifier.query.filter(Notifier.id == id).first_or_404()
    form = NotifierForm()
    if form.validate_on_submit():
        nf.title = form.title.data
        nf.content = process_html(form.content.data).text
        if form.status.data.status == 'Histórico' and nf.status.status == 'Ativo':
            nf.closed_at = convert_datetime_to_local(datetime.utcnow())
            # nf.level = NotifierLevel.query.filter(NotifierLevel.level_bootstrap == 'info').first()
        if form.status.data.status == 'Ativo' and nf.status.status == 'Histórico':
            nf.closed_at = None
        nf.level = form.level.data
        nf.status = form.status.data
        nf.priority = form.priority.data
        
        nf.topics.extend(form.topics.data)
        nf.sub_topics.extend(form.sub_topics.data)
        nf.updater_user_id = current_user.id
        if nf.autoload != form.autoload.data:
            if form.autoload.data is True:
                temp_nf = Notifier.query.filter(Notifier.sub_topics.contains(*form.sub_topics.data), Notifier.autoload == True).first()
                if not temp_nf is None:
                    # status = NotifierStatus.query.filter(NotifierStatus.status == 'Histórico').first()
                    # temp_nf.status =status
                    temp_nf.autoload = False
        nf.autoload = form.autoload.data
        try:
            db.session.commit()
            flash('Notificação criada com sucesso', category='success')
            return redirect(url_for('notifier.view', id=nf.id))
        except Exception as e:
            app.logger.error(app.config.get('_ERRORS').get('DB_COMMIT_ERROR'))
            app.logger.error(e)
            db.session.rollback()
            return render_template('edit.html', form=form, title='Editar', notifier=True)
    form.title.data = nf.title
    form.content.data = nf.content
    form.status.data = nf.status
    form.priority.data = nf.priority
    form.topics.data = nf.topics
    form.autoload.data = nf.autoload
    form.sub_topics.data = nf.sub_topics
    form.level.data = nf.level
    return render_template('edit.html', form=form, title='Editar', notifier=True)

@bp.route('/deactive/<int:id>', methods=['GET', 'POST'])
@login_required
@roles_accepted('admin', 'support')
def deactive(id: int):
    confirm = request.form.get('confirm', False)
    if confirm != 'true':
        return jsonify({
            'status': 'error',
            'message': 'not confirmed'
        }), 404
    notifier = Notifier.query.filter(Notifier.id == id).first()
    if notifier is None:
        return jsonify({
            'status': 'error',
            'message': 'notification not found'
        }), 404
    try:
        db.session.delete(notifier)
        db.session.commit()
        return jsonify({
            'id': id,
            'status': 'success'
        }),200
    except Exception as e:
        app.logger.error(app.config.get('_ERRORS').get('DB_COMMIT_ERROR'))
        app.logger.error(e)
        db.session.rollback()
        return jsonify({
            'status': 'error',
            'message': 'database error'
        }), 404
        

app/blueprints/question.py
from datetime import datetime
from flask import (
    current_app as app,
    Blueprint,
    render_template,
    url_for,
    redirect,
    flash,
    json,
    Markup,
    abort,
    request,
    escape,
    g,
    jsonify,
    session,
)
from flask.globals import current_app
from flask_security import login_required, current_user, roles_accepted
from app.blueprints.admin import sub_topic
from app.core.db import db
from app.models.history import QuestionHistory
from app.models.wiki import (
    Question,
    QuestionLike,
    QuestionSave,
    QuestionView,
    SubTopic,
    Tag,
    Topic,
)
from app.models.security import User
from app.models.app import Network
from app.models.search import Search
from app.utils.sql import unaccent
from app.utils.kernel import convert_datetime_to_local, strip_accents, process_value
from app.utils.html import process_html
from app.forms.question import (
    QuestionAnswerForm,
    CreateQuestion,
    QuestionApproveForm,
    QuestionEditAndApproveForm,
)

from app.utils.routes import counter
from sqlalchemy import desc, func, nullslast


from app.forms.question import QuestionEditForm, QuestionSearchForm, QuestionForm

bp = Blueprint("question", __name__, url_prefix="/duvidas/")


@bp.route("/")
@bp.route("/index")
@counter
def index():
    page = request.args.get("page", 1, type=int)
    if not session.get("AccessType", False):
        return redirect(url_for("main.index"))
    sub_topic = request.args.get("sub_topic", False)
    if not sub_topic is False:
        sub_topic = SubTopic.query.filter(SubTopic.name == sub_topic).first()
        if sub_topic is None:
            return abort(404)
    topics = Topic.query.filter(Topic.name.ilike(session.get("AccessType"))).all()
    search_form = QuestionSearchForm()
    if current_user.is_authenticated and current_user.is_support:
        query = (
            db.session.query(Question)
            .join(Question.view)
            .filter(Question.answer_approved == True, Question.active == True)
        )  # .order_by(Question.create_at.desc())
    else:
        query = (
            db.session.query(Question)
            .join(Question.view)
            .filter(Question.answer_approved == True, Question.active == True)
            .join(Question.topics)
            .join(Question.view)
            .filter(Topic.id.in_([_.id for _ in topics]))
        )  # .order_by(Question.create_at.desc())
    # query = Question.query.filter(Question.answer_approved==True, Question.topic_id.in_([_.id for _ in topics])).order_by(Question.create_at.desc())
    if not sub_topic is False:
        paginate = (
            query.group_by(Question)
            .order_by(func.count(QuestionView.id).desc())
            .filter(Question.sub_topics.contains(sub_topic))
            .paginate(per_page=app.config.get("QUESTIONS_PER_PAGE"), page=page)
        )
    else:
        paginate = (
            query.group_by(Question)
            .order_by(func.count(QuestionView.id).desc())
            .paginate(per_page=app.config.get("QUESTIONS_PER_PAGE"), page=page)
        )
    iter_pages = list(paginate.iter_pages())
    first_page = iter_pages[0] if len(iter_pages) >= 1 else None
    last_page = paginate.pages if paginate.pages > 0 else None

    url_args = dict(request.args)
    url_args.pop("page") if "page" in url_args.keys() else None

    return render_template(
        "question.html",
        pagination=paginate,
        cls_question=Question,
        form=search_form,
        mode="views",
        first_page=first_page,
        last_page=last_page,
        sub_topics=SubTopic.query,
        url_args=url_args,
    )


@bp.route("/search/", methods=["GET", "POST"])
@counter
def search():
    page = request.args.get("page", 1, type=int)
    search_query = False

    if g.question_search_form.validate():
        if not session.get("AccessType", False):
            return redirect(url_for("main.index"))
        topics = Topic.query.filter(Topic.name.ilike(session.get("AccessType"))).all()
        sub_topics = g.question_search_form.filter.data
        if not sub_topics:
            sub_topics = SubTopic.query.all()
        if current_user.is_authenticated and current_user.is_support:
            topics = []
        q = (
            Question.search(
                g.question_search_form.q.data,
                pagination=False,
                sub_topics=sub_topics,
                topics=topics,
            )
            .filter(Question.answer_approved == True)
            .order_by(desc("similarity"))
        )  # .join(QuestionView.question, full=True).filter(Question.answer_approved==True).order_by(QuestionView.count_view.desc())

        paginate = q.paginate(
            per_page=app.config.get("QUESTIONS_PER_PAGE", 1), page=page
        )
        search_query = strip_accents(g.question_search_form.q.data)
        search = Search.query.filter(unaccent(Search.text).ilike(search_query)).first()
        if search is None:
            search = Search()
            search.text = strip_accents(g.question_search_form.q.data).lower()
            # question = Question.query.filter(Question.question.ilike(g.question_search_form.q.data)).first()
            # if not question is None:
            #     search.question_id = question.id
            db.session.add(search)
            try:
                db.session.commit()
            except Exception as e:
                db.session.rollback()
                app.logger.error(app.config.get("_ERRORS").get("DB_COMMIT_ERROR"))
                app.logger.error(e)
                return abort(500)
        else:
            if current_user.is_authenticated:
                search.add_search(current_user.id)
            else:
                search.add_search()
            # search.add_count()
        iter_pages = list(paginate.iter_pages())
        first_page = (
            iter_pages[0] if len(iter_pages) >= 1 else None
        )  # url_for('.search',page=iter_pages[0], q= g.question_search_form.q.data)
        last_page = (
            paginate.pages if paginate.pages > 0 else None
        )  # url_for('.search',page=iter_pages[-1] if iter_pages[-1] != first_page else None, q= g.question_search_form.q.data)
        if paginate.total == 0:
            form = CreateQuestion()
            topic = Topic.query.filter(
                Topic.name.ilike(session.get("AccessType"))
            ).first()
            if topic is None:
                return abort(505)
            if form.validate_on_submit():
                question = Question.query.filter(
                    Question.question.ilike(form.question.data)
                ).first()
                if not question is None:
                    form.question.errors.append("Dúvida já cadastrada")
                if not form.errors:
                    if current_user.is_authenticated:
                        user = current_user
                    else:
                        user = User.query.filter(
                            User.id == app.config.get("USER_ANON_ID", False)
                        ).first()

                    question = Question()
                    question.question = form.question.data
                    question.topics.append(topic)
                    question.sub_topics.append(form.sub_topic.data)
                    question.create_user_id = user.id
                    question.question_network_id = g.ip_id
                    question.active = False
                    db.session.add(question)
                    try:
                        db.session.commit()
                        flash("Dúvida cadastrada com sucesso!", category="success")
                        return redirect(url_for("question.index"))
                    except Exception as e:
                        db.session.rollback()
                        app.logger.error(
                            app.config.get("_ERRORS").get("DB_COMMIT_ERROR")
                        )
                        app.logger.error(e)
                        return abort(500)
            if search_query is not False:
                form.question.data = strip_accents(g.question_search_form.q.data)
        else:
            form = False

        return render_template(
            "question.html",
            mode="search",
            cls_question=Question,
            pagination=paginate,
            first_page=first_page,
            last_page=last_page,
            form=form,
            url_arguments={"q": g.question_search_form.q.data},
        )
    return render_template(
        "question.html",
        mode="search",
        cls_question=Question,
        form=False,
        url_arguments={"q": g.question_search_form.q.data},
    )


@bp.route("/view/<int:id>")
@counter
def view(id=None):
    # TODO
    if current_user.is_anonymous:
        # question = db.session.query(Question
        # ).filter(Question.id == id
        # ).join(Question.topics
        # ).filter(Topic.id == g.topic.id, Question.active == True
        # ).first_or_404()
        question = (
            db.session.query(Question)
            .filter(Question.id == id, Question.active == True)
            .first_or_404()
        )
        if not question.has_topic(g.topic):
            # _topic_name = f'<p class="font-weight-bold">{question.topic_name}</p>'
            flash(
                Markup(
                    f"A pergunta que você tentou acessar está disponível para <b>{question.topic_name}</b>, selecione o módulo correto para acessar a pergunta."
                ),
                category="danger",
            )
            return redirect(url_for("main.select_access", next=request.path))

    else:
        question = Question.query.filter(Question.id == id).first_or_404()
    question_history = question.history.all()
    if len(question_history) == 0:
        question_history = None

    if current_user.is_authenticated:
        user_id = current_user.id
    else:

app/templates/_transaction.html
{% block app_content %}

{% if transaction_dict %}

<h3 class="page-header">Visualizar transação {{transaction_dict['Transação']}}</h3>

<div class="row">
  {% for key, value in transaction_dict.items() %}
    <div class="col-md-4">
      <p><strong>{{key}}</strong></p>
      <p>{{value}}</p>
    </div>
  {% endfor %}
  </div> 
  
  {% endif %}

  

{% endblock %}

app/templates/admin.html
{% import "macros/main.html" as macros %}
{% import "macros/form.html" as forms %}
{% extends 'base.html' %}
{% block app_content %}
<div id="list" class="row">
    {% if form is defined %}
    <form action="" method="GET" role="form">
        <div class='form-group'>
            {% if form.search is defined %}
            <div class="col-md-2">
            {{ forms.render_field(form.search, size=5, class='form-select',
            placeholder='Buscar...', nolabel=true, type='search', **{'aria-label':"Buscar",
            'aria-describedby':"submit"})}}
            </div>
            {% endif %}
            <br>
            {% if form.topic is defined %}
            {{ forms.render_field(form.topic, class='form-select', class='selectpicker', nolabel=true,
            multiple=true,
            title='Selecionar Tópico', **{'data-actions-box':"true", 'data-style':"btn-primary",
            'data-selected-text-format':"count"})}}
            {% endif %}
            {% if form.sub_topic is defined %}
            {{ forms.render_field(form.sub_topic, class='form-select', class='selectpicker', nolabel=true,
            multiple=true,
            title='Selecionar Sub-Tópico', **{'data-actions-box':"true", 'data-style':"btn-primary",
            'data-selected-text-format':"count"})}}
            {% endif %}

            {% if form.tag is defined %}
            {{ forms.render_field(form.tag, class='form-select', class='selectpicker', nolabel=true, multiple=true,
            title='Selecionar Marcação', **{'data-actions-box':"true", 'data-style':"btn-primary",
            'data-selected-text-format':"count"})}}
            {% endif %}
            {% if form.who_answer is defined %}
            {{ forms.render_field(form.who_answer, class='form-select', class='selectpicker', nolabel=true, multiple=true,
            title='Selecionar Marcação', **{'data-actions-box':"true", 'data-style':"btn-primary",
            'data-selected-text-format':"count"})}}
            {% endif %}
            
            {% if form.active is defined %}
            <br>
            {{ forms.render_field(form.active, class='form-select', class='selectpicker',
            title='Selecionar Marcação', **{'data-actions-box':"true", 'data-style':"btn-primary",
            'data-selected-text-format':"count"})}}
            {% endif %}
            <br>

            {% if form.type is defined %}
            <br>
            {{ forms.render_field(form.type, class='form-select', class='selectpicker',
            title='Selecionar Marcação', **{'data-actions-box':"true", 'data-style':"btn-primary",
            'data-selected-text-format':"count"})}}
            {% endif %}

            {% if form.approved is defined %}
            <br>
            {{ forms.render_field(form.approved, class='form-select', class='selectpicker',
            title='Selecionar Marcação', **{'data-actions-box':"true", 'data-style':"btn-primary",
            'data-selected-text-format':"count"})}}
            {% endif %}

            <br>
            {{ form.submit(class='btn btn-success') }}
        </div>
    <hr>
    </form>
    {% endif %}
    <!-- {{current_user}} -->
    {{ macros.render_table(cls_table, pagination, page_name, url_arguments = url_args if url_args is defined else {}, order_type=order_type, order=order, mode=mode, type=type,
    user = current_user, no_view=false, order_type_inverse=order_type_inverse) }}
    {{ macros.render_pagination(pagination, first_page, last_page, endpoint, url_arguments = url_args if url_args is defined else {}, order=order, order_type=order_type, order_type_inverse=order_type_inverse)}}
    
</div>
{% endblock %}

app/templates/answer.html
{% extends 'base.html' %}
{% import "macros/form.html" as macros %}
{% block styles %}
{{ super()}}
<link href="{{url_for('static', filename='css/simplemde/simplemde-theme-dark.min.css')}}" rel="stylesheet">
{% if article %}
<!-- <link href="{{url_for('static', filename='css/editormd/editormd.css')}}" rel="stylesheet" /> -->

{% endif %}
{% endblock %}
{% block app_content %}
{% if form %}
<div class="col-md-8">
    <form action="" method="POST">
        {{ form.csrf_token }}
        {{ macros.render_field(form.question, style="height: 120px;", class='form-control')}}
        {{ macros.render_field(form.answer, size=256, class='form-control', placeholder='Reposta')}}
        {{ macros.render_field(form.tag, class='form-select', class='selectpicker', nolabel=true, multiple=true,
        **{'data-style':"btn-primary", 'data-selected-text-format':"count", "data-live-search":"true", "data-size":"5", 'data-width':"auto"})}}
        <br>
        <br>
        {{ macros.render_field(form.topic, class='form-select', class='selectpicker', nolabel=true, multiple=true,
        **{'data-actions-box':"true", 'data-style':"btn-primary", 'data-selected-text-format':"count"})}}

        <br>
        <br>
        {{ macros.render_field(form.sub_topic, class='form-select', class='selectpicker', nolabel=true, multiple=true,
        **{'data-actions-box':"true", 'data-style':"btn-primary", 'data-selected-text-format':"count"})}}
        <br>
        <br>
        {#{% if approve is defined %}
        {{ macros.render_field(form.approve, class='form-check-input')}}
        <br>
        {% endif %}#}
        {% if answer is defined %}
        {{ form.submit(class='btn btn-success') }}
        {% elif approve is defined %}
        {{ form.approve(class='btn btn-success') }}
        {{ form.repprove(class='btn btn-danger') }}
        <br> 
        <br> 
        {{ macros.render_field(form.answered_by, size=32, class='form-control', placeholder='Titulo') }}
        {% endif %}

    </form>
</div>
{% endif %}
{% endblock %}


{% block scripts %}
{{ super() }}

<script src="{{url_for('static', filename='js/simplemde/simplemde.min.js')}}" {#nonce="{{ csp_nonce() }}" #}></script>

<script type="text/javascript" {#nonce="{{ csp_nonce() }}#}">


    element = document.getElementById("text");
    if (element == null) {
        element = document.getElementById("answer");
    }
    var simplemde = new SimpleMDE({
        element: element,
        autosave: true,
        forceSync: true,
        renderingConfig: {
            singleLineBreaks: true,
            codeSyntaxHighlighting: true,
        },
        shortcuts: {
            drawTable: "Cmd-Alt-T"
        },
        showIcons: ["code", "table"]
    });
</script>
{% endblock %}

app/templates/dashboard.html
{% extends 'base.html' %}

{% block app_content %}

{{ dash | safe }}

{% endblock %}

app/templates/files.html
{% import "macros/main.html" as macros %}
{% import "macros/form.html" as forms %}
{% extends 'base.html' %}
{% block app_content %}
<div id="list" class="row">
    {% if pagination is defined %}
    <div class="col-md-6">
        {% if title_name is defined %}
        <h2>{{ title_name }}</h2>
        
        {% else %}
        <h2>Arquivos</h2>
        {% endif %}
    </div>
    <hr>
    <div class="container-fluid border rounded p-3">
        <div class="list-group">
            {% for item in pagination.items %}
            <a href="{{ url_for('file_pdf.view', id=item.id) }}" class="list-group-item list-group-item-action text-primary" aria-current="true">
                <i class="fas fa-file-pdf"></i>
                {{item.title}} 
                <div class="float-end">
                    Enviado em {{ item.get_reference_date}}
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
    
    {% endif %}
    {#<div class="container">
        <div class="row">
            <h6 class="text-muted fw-normal text-uppercase">Tópico</h6>
            <div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
                {% if 'topic' in request_args.keys() %}
                {% set _rqa_topic = request_args %}
                {% endif %}
                {% for tp in _topic %}
                <a href="{{ url_for(endpoint, topic=tp.name)}}" class='btn btn-primary border'>{{tp.name}}</a>
                {% endfor %}
            </div>
        </div>
    </div>#}
    {{ macros.render_table(cls_table, pagination, page_name, order_type=order_type, mode=mode, type=type,user=current_user) }}
    {{ macros.render_pagination(pagination, first_page, last_page, endpoint, url_arguments = url_args if url_args is defined else {})}}
</div>
{% endblock %}

app/templates/notifier.html
{% extends 'base.html' %}

{% block app_content %}

<div class="container-sm col-10">

    {% if notification_dict is defined %}
    
    {% include '_notifier.html' %}
    {% else %}
    
    <ul class="nav nav-tabs" id='notifierTab' role='notifierList'>
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id='active-tab' data-bs-toggle='tab' data-bs-target="#active" type="button"
                role='tab' aria-controls="active" aria-selected="true">Ativos</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id='history-tab' data-bs-toggle='tab' data-bs-target="#history" type="button"
                role='tab' aria-controls="history" aria-selected="false">Histórico</button>
        </li>
    </ul>
    <div class="row my-3 tab-content">
        {% if notices_active is defined %}
        <div class="tab-pane fade show active border border-primary pb-3 rounded mb-2" id='active' role='tabpanel'
            aria-labelledby="active-tab">
            
            {% for notice in notices_active %}
            <div class="row">

                <div class="mt-2">
                    {% for topic in notice.topics_name.split(',') %}
                    <span class="badge bg-info mt-0 float-start">{{topic}}</span>
                    {% endfor %}
                    <a class="edit text-decoration-none float-end" id="edit_34170"
                        href="{{ url_for('notifier.edit', id=notice.id)}}"><i class="fas fa-edit"></i></a>
                </div>
            </div>
            <div class="row m-3">
                <div class="row">
                    <h5 class="fw-normal text-success">{{notice.title}}</h5>
                </div>
                <div class="row">
                    <span class="fw-normal text-muted">{{notice.content}}</span>
                </div>
            </div>
            <div class="row d-flex justify-content-around m-3">
                <div class="col d-flex text-muted">
                    Criado {{notice.get_create_time_elapsed}}
                </div>
                <div class="col d-flex justify-content-around text-muted">
                    Prioridade: {{notice.priority.priority}}
                </div>
                <!-- <div class="col d-flex justify-content-around">
                    3
                </div> -->
            </div>
            <hr>
            {% endfor %}
            
        </div>
        {% endif %}
        {% if notices_history is defined %}
        <div class="tab-pane fade border border-secondary pb-3 rounded mb-3" id='history' role='tabpanel'
            aria-labelledby="history-tab">
            
            {% for notice in notices_history %}
            {% for topic in notice.topics_name %}
            <span class="badge bg-secondary mt-3 float-end">{{topic}}</span>
            {% endfor %}
            <div class="row m-3">
                <div class="row">
                    <h5 class="fw-normal text-secondary">{{notice.title}}</h5>
                </div>
                <div class="row">
                    <span class="fw-normal">{{notice.content}}</span>

                </div>
            </div>
            <div class="row d-flex justify-content-around m-3">
                <div class="col d-flex">
                    {{notice.get_create_time_elapsed}}
                </div>
                <div class="col d-flex justify-content-around">
                    Prioridade: {{notice.priority.priority}}
                </div>
                <!-- <div class="col d-flex justify-content-around">
                    3
                </div> -->
            </div>
            <hr>
            {% endfor %}
            
        </div>
        {% endif %}

        {% endif %}
    </div>

    {% endblock %}

app/templates/popover_transaction.html
{% if %}

<a class="btn" rel="popover" data-img="//placehold.it/400x200">Image 1</a>

app/templates/search.html
{% extends 'base_question.html' %}
{% from "macros/form.html" import render_field %}
{% from "macros/main.html" import render_pagination %}

{% block question_content %}

{% if pagination.total == 0 %}
Nenhum resultado encontrado
<div class="d-flex justify-content-between mt-5">
        <a type="button" class="btn btn-info" href="{{url_for('question.index')}}">Voltar</a>
</div>
{% else %}
<!-- {% for item in pagination.items %}
<div class="alert alert-dark" role="alert">
        <a href="{{url_for('question.view', id=item[0].id)}}"
                class='badge bg-info text-dark text-wrap text-break text-decoration-none'>
                {{item[0].question}}</a>
        {% if current_user.can_edit %}
        <a href="{{url_for('question.remove', id=item[0].id)}}"
                class="text-decoration-none btn btn-danger btn-sm float-end"><i class="icon-remove"></i></a>
        <a href="{{url_for('question.edit', id=item[0].id)}}"
                class="text-decoration-none btn btn-success btn-sm float-end"><i class="icon-edit"></i></a>
        {% endif %}

</div>
{% endfor %} -->

{% set mode = 'search' %}
{% include '_question.html' %}
{{ render_pagination(pagination, first_page, last_page, 'main.search', url_arguments=url_arguments)}}
{% endif %}
{% endblock %}